# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 350)
        Dialog.setStyleSheet("background-color: #111111;")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(398, 0, 2, 501))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 370, 60))
        self.lineEdit.setStyleSheet("color: #ffffff;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 160, 181, 81))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: #ffffff;\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    background-color: #111111;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #ffffff;\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    background-color: #222222;\n"
"    border: none;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 280, 370, 60))
        self.label.setStyleSheet("color: #ffffff;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(420, 60, 370, 60))
        self.lineEdit_2.setStyleSheet("color: #ffffff;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(420, 280, 370, 60))
        self.label_2.setStyleSheet("color: #ffffff;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 160, 181, 81))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: #ffffff;\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    background-color: #111111;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #ffffff;\n"
"    font: 18pt \"MS Shell Dlg 2\";\n"
"    background-color: #222222;\n"
"    border: none;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 371, 31))
        self.label_3.setStyleSheet("color: #ffffff;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(420, 20, 371, 31))
        self.label_4.setStyleSheet("color: #ffffff;\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Translate"))
        self.pushButton_2.setText(_translate("Dialog", "Translate"))
        self.label_3.setText(_translate("Dialog", "IN"))
        self.label_4.setText(_translate("Dialog", "OUT"))